### PR TITLE
some initial code commits

### PR DESCRIPTION
**Pull request by karthikrk1**
Change log:

Added the `django_restframework`, `django_restframework.authtoken` and `projects_api` to the settings.py to enable the app in our project.

### CODE REVIEW

**Comment by karthikrk1** [comment]
More commits to be added

**Comment by karthikrk1** [comment]
@karthikram1 - assigining you. Will update once ready for review

**Comment by karthikrk1** [comment]
Some more additions to the branch

**Comment by karthikrk1** [comment]
Added commits for the day.. @karthikram1 review and close as needed

**Review by karthikram1 — APPROVED** [review]
LGTM. Tested and Working

**Pull request merged**
